services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=watchmen
      - POSTGRES_PASSWORD=needs_watch
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: